/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2013-12-28 21:07:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.googlePlus;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class GooglePlusLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Facebook Login Page</title>\n");
      out.write("\t\t<!-- Bootstrap -->\n");
      out.write("\t\t<link href=\"/BWeb/css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t\t<link href=\"/BWeb/css/additional.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t\t<script src=\"/BWeb/js/googlePlus/googlePlus.js\"></script>\n");
      out.write("\t\t<script src=\"/BWeb/js/jquery-1.9.1.js\"></script>\n");
      out.write("\t\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\tfunction signinCallback(authResult) {\n");
      out.write("\t\t\tdebugger;\n");
      out.write("\t\t    if (authResult['status']['signed_in']) {\n");
      out.write("\t\t    \t// Update the app to reflect a signed in user\n");
      out.write("\t\t    \t// Hide the sign-in button now that the user is authorized, for example:\n");
      out.write("\t\t    \tdocument.getElementById('signinButton').setAttribute('style', 'display: none');\n");
      out.write("\t\t    \tconsole.log(\"Token:\" + authResult.access_token);\n");
      out.write("\t\t    \t// Ajax call to the Init action to init the plus client, then go to the profile action\n");
      out.write(" \t\t\t\t$.ajax({\n");
      out.write(" \t\t\t\t\ttype : \"GET\",\n");
      out.write(" \t\t\t\t\turl : \"http://localhost:8080/BWeb/gp_GooglePlusInit.do\",\n");
      out.write(" \t\t\t\t\tdata : {access_token : authResult.access_token},\n");
      out.write(" \t\t\t\t\tdataType : \"text\",\n");
      out.write(" \t\t\t\t\tsuccess : function(result) {\n");
      out.write(" \t\t\t\t\t\tdebugger;\n");
      out.write(" \t\t\t\t\t\twindow.location = (\"http://localhost:8080/BWeb/gp_GooglePlusProfile.do\");\n");
      out.write(" \t\t\t\t\t}\n");
      out.write(" \t\t\t\t});\t\n");
      out.write(" \t\t\t} else {\n");
      out.write("\t\t\t    // Update the app to reflect a signed out user\n");
      out.write("\t\t\t    // Possible error values:\n");
      out.write("\t\t\t    //   \"user_signed_out\" - User is signed-out\n");
      out.write("\t\t\t    //   \"access_denied\" - User denied access to your app\n");
      out.write("\t\t\t    //   \"immediate_failed\" - Could not automatically log in the user\n");
      out.write("\t\t    \tconsole.log('Sign-in state: ' + authResult['error']);\n");
      out.write("\t\t    }\n");
      out.write("\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t<div class=\"container account-wall\" style=\"text-align: center;\">\n");
      out.write("\t\t\t<h2 class=\"form-signin-heading\">Sign in</h2>\n");
      out.write("\t\t\t<h4 class=\"text-muted\">Connect with your google+ account</h4>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<img alt=\"facebook icon\" src=\"/BWeb/img/GooglePlus.jpg\" style=\"width: 73px;height: 73px;\">\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<br/>\n");
      out.write("\t\t\t<span id=\"signinButton\">\n");
      out.write("\t\t\t\t<span\n");
      out.write("\t\t\t\t    class=\"g-signin\"\n");
      out.write("\t\t\t\t    data-callback=\"signinCallback\"\n");
      out.write("\t\t\t\t    data-clientid=\"217653803775-8hkvkhcamc51l39vk08bu4nbck8pqj7d.apps.googleusercontent.com\"\n");
      out.write("\t\t\t\t    data-cookiepolicy=\"single_host_origin\"\n");
      out.write("\t\t\t\t    data-requestvisibleactions=\"http://schemas.google.com/AddActivity\"\n");
      out.write("\t\t\t\t    data-scope=\"https://www.googleapis.com/auth/plus.login\">\n");
      out.write("\t\t\t\t</span>\n");
      out.write("\t\t\t</span>\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Place this asynchronous JavaScript just before your </body> tag -->\n");
      out.write("\t    <script type=\"text/javascript\">\n");
      out.write("\t      (function() {\n");
      out.write("\t       var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;\n");
      out.write("\t       po.src = 'https://apis.google.com/js/client:plusone.js';\n");
      out.write("\t       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);\n");
      out.write("\t     })();\n");
      out.write("\t    </script>\n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t    \n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
