/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-01-04 01:07:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>Login</title>\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t\t<!-- Bootstrap -->\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t\t<link href=\"css/social/welcome-page.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t\t<link href=\"/BWeb/css/login.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t        <div class=\"span12\">\n");
      out.write("\t\t    \t\t<div class=\"\" id=\"loginModal\">\n");
      out.write("\t\t              <div class=\"modal-header\">\n");
      out.write("\t\t                <h3>Have an Account?</h3>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"modal-body\">\n");
      out.write("\t\t                <div class=\"well\">\n");
      out.write("\t\t                  <ul class=\"nav nav-tabs\">\n");
      out.write("\t\t                    <li class=\"active\"><a href=\"#login\" data-toggle=\"tab\">Login</a></li>\n");
      out.write("\t\t                    <!-- <li><a href=\"#create\" data-toggle=\"tab\">Create Account</a></li> -->\n");
      out.write("\t\t                  </ul>\n");
      out.write("\t\t                  <div id=\"myTabContent\" class=\"tab-content\">\n");
      out.write("\t\t                    <div class=\"tab-pane active in\" id=\"login\">\n");
      out.write("\t\t                      <form class=\"form-horizontal\" action='login.do' method=\"POST\">\n");
      out.write("\t\t                        <fieldset>\n");
      out.write("\t\t                          <div id=\"legend\">\n");
      out.write("\t\t                            <legend class=\"\">Login or Register</legend>\n");
      out.write("\t\t                          </div> \n");
      out.write("\t\t                          \n");
      out.write("\t\t                          ");

								      List<String> errors = (List<String>)request.getAttribute("errors");
									  if (errors != null && errors.size() != 0) {
								  
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t  <div class=\"alert alert-error\">\n");
      out.write("\t\t\t\t\t\t\t\t  ");
      out.print(errors.get(0) );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t  ");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t  ");
 
									  } 
								  
      out.write("\n");
      out.write("\t\t                          \n");
      out.write("\t\t                             \n");
      out.write("\t\t                          <div class=\"control-group\">\n");
      out.write("\t\t                            <!-- Username -->\n");
      out.write("\t\t                            <label class=\"control-label\"  for=\"username\">Username</label>\n");
      out.write("\t\t                            <div class=\"controls\">\n");
      out.write("\t\t                              <input type=\"text\" id=\"username\" name=\"userName\" placeholder=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                          </div>\n");
      out.write("\t\t     \n");
      out.write("\t\t                          <div class=\"control-group\">\n");
      out.write("\t\t                            <!-- Password-->\n");
      out.write("\t\t                            <label class=\"control-label\" for=\"password\">Password</label>\n");
      out.write("\t\t                            <div class=\"controls\">\n");
      out.write("\t\t                              <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                          </div>\n");
      out.write("\t\t     \n");
      out.write("\t\t     \n");
      out.write("\t\t                          <div class=\"control-group\">\n");
      out.write("\t\t                            <!-- Button -->\n");
      out.write("\t\t                            <div class=\"controls\">\n");
      out.write("\t\t                              <input class=\"btn btn-success\" type=\"submit\" name=\"action\" value=\"Login\"/>\n");
      out.write("\t\t                              <input class=\"btn btn-success\" type=\"submit\" name=\"action\" value=\"Register\"/>\n");
      out.write("\t\t                            </div>\n");
      out.write("\t\t                          </div>\n");
      out.write("\t\t                        </fieldset>\n");
      out.write("\t\t                      </form>                \n");
      out.write("\t\t                    </div>\n");
      out.write("\t\t                    <div class=\"tab-pane fade\" id=\"create\">\n");
      out.write("\t\t                      <form id=\"tab\">\n");
      out.write("\t\t                        <label>Username</label>\n");
      out.write("\t\t                        <input type=\"text\" value=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                        <label>First Name</label>\n");
      out.write("\t\t                        <input type=\"text\" value=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                        <label>Last Name</label>\n");
      out.write("\t\t                        <input type=\"text\" value=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                        <label>Email</label>\n");
      out.write("\t\t                        <input type=\"text\" value=\"\" class=\"input-xlarge\">\n");
      out.write("\t\t                        <label>Address</label>\n");
      out.write("\t\t                        <textarea value=\"Smith\" rows=\"3\" class=\"input-xlarge\">\n");
      out.write("\t\t                        </textarea>\n");
      out.write("\t\t     \n");
      out.write("\t\t                        <div>\n");
      out.write("\t\t                          <button class=\"btn btn-primary\">Create Account</button>\n");
      out.write("\t\t                        </div>\n");
      out.write("\t\t                      </form>\n");
      out.write("\t\t                    </div>\n");
      out.write("\t\t                </div>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t        </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery.js\"></script>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
