/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2013-11-26 05:56:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>Welcome page</title>\n");
      out.write("\t<script type=\"text/javascript\" src=\"ajax.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"search-suggest.js\"></script>\n");
      out.write("\t<!-- Bootstrap -->\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\t\n");
      out.write("\t<link href=\"css/additional.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<h1 style=\"color: red;\"> Welcome ");
      out.print( request.getParameter("userName") );
      out.write("</h1>\n");
      out.write("\t\t<h4>Search username here.</h4>\n");
      out.write("\t    <div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-sm-4 col-md-4\">\n");
      out.write("\t            <div class=\"panel panel-default\">\n");
      out.write("\t                <div class=\"panel-body\">                \n");
      out.write("\t                    <input type=\"text\" id=\"username\" name=\"username\" onkeyup=\"searchSuggest(this);\" autocomplete=\"off\"/>\n");
      out.write("\t\t\t\t\t\t<div id=\"search_suggest\"></div>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\tClick <a href=\"logout.do\">here</a> to logout.\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t    <div class=\"row\">\n");
      out.write("\t        <div class=\"col-xs-12 col-sm-12 col-md-6\">\n");
      out.write("\t            <div class=\"panel panel-primary\">\n");
      out.write("\t                <div class=\"panel-body\">\n");
      out.write("\t                    <div class=\"row\">\n");
      out.write("\t                        <div class=\"col-xs-6 col-sm-6 col-md-6 separator social-login-box\"> <br />\n");
      out.write("\t                            <a href=\"http://www.jquery2dotnet.com\" class=\"btn facebook btn-primary\" role=\"button\">Facebook</a>\n");
      out.write("\t                            <br />\n");
      out.write("\t                            <br />\n");
      out.write("\t                            <form action=\"tw_OauthRequestToken.do\" method=\"POST\">\n");
      out.write("\t                            \t<input class=\"btn twitter btn-info\" type=\"submit\" name=\"action\" value=\"Twitter\" />\n");
      out.write("\t                            </form>\n");
      out.write("\t                            \n");
      out.write("\t                            <a href=\"Twitter.jsp\" class=\"btn twitter btn-info\" role=\"button\">Twitter</a>\n");
      out.write("\t                        </div>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("    </div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
